# Generated by Django 3.1.1 on 2023-09-18 23:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Cheese'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True, verbose_name='Cheese Address'),
        ),
    ]
